FROM golang:1.16-alpine as build-stage

WORKDIR /usr/src/app

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' && \
    adduser -D appuser

FROM scratch

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app .

COPY --from=build-stage /etc/passwd /etc/passwd

USER appuser

CMD ["./server"]