version: '3'

services: 
  backend:
    image: backend
    ports: 
      - 8080:8080
    container_name: compose-backend
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
  frontend:
    image: frontend
    ports: 
      - 5000:5000
    container_name: compose-frontend
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    container_name: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    volumes: 
      - ./database:/var/lib/postgresql/data